### ISSUE TITLE
Template not used after upgrade to 1.0.1

### ISSUE THREAD

**Issue by thijstriemstra** [dstegelman/django-downtime#26]
With 0.3.3 the unit test in my project detects the custom template I use for django-downtime:

```python
for template in ['downtime/downtime.html', 'base.html']:
    self.assertTemplateUsed(response, template)
```
but with 1.0.1 it always uses the builtin template:
```python
AssertionError: Template 'base.html' was not a template used to render the response. Actual template(s) used: downtime/downtime.html
```
Any ideas why this changed?

**Comment by dstegelman** [comment]
Templates were not actually getting shipped before, which was corrected with this release.  You should be able to override it though.  

Hmm I'll have to dig in this further.

**Comment by dstegelman** [comment]
I was able to add an override to the demo application.

https://github.com/dstegelman/django-downtime/commit/426f0681be81e920d4cd1c11d9fdd12be5085d59

Can you double check your settings and inheritance to make sure that template is correct?  I"m not seeing an issue here.

Re-open if you are still having trouble with any more detail that you can provide.
