### ISSUE TITLE
Management command to go down and come up again.

### ISSUE THREAD

**Issue by philippeowagner** [dstegelman/django-downtime#29]
Hi @dstegelman 

What do you think about a management command to control the downtime from CI systems? Going down before the deployment starts using 

    python manage.py downtime_start

and then 

    python manage.py downtime_end

to come up  to normal mode. Would you merge this feature?

**Comment by dstegelman** [comment]
Yes, that sounds like an interesting feature.

**Comment by dstegelman** [comment]
Released in 1.0.2

**Comment by philippeowagner** [comment]
Thanks for adding the feature.
