### ISSUE TITLE
Django 1.8.6 and migrations

### ISSUE THREAD

**Issue by midnightlynx** [dstegelman/django-downtime#36]
Django 1.8.6 now gives an error message instead of migrating, if an app has both south migrations and django migrations.

**Comment by dstegelman** [comment]
Right, but only if *south* migrations are in the *migrations* module.  We moved these to *south_migrations* many releases ago.

https://code.djangoproject.com/ticket/25618

I ran a check and migrated just fine.

**Comment by midnightlynx** [comment]
Oops. Now that I look again, we were using an outdated fork.
