### ISSUE TITLE
Add context to template

### ISSUE THREAD

**Issue by scottwoodall** [dstegelman/django-downtime#39]
Greetings! This is a nice utility/project you've written. I was wondering if you would be open for a pull request that added some context into the `downtime/downtime.html` template.

The idea being that a message column be added to the model which could be displayed to the user when downtime is active, along with the start/end time of the outage so users knew when to check back. The existing `downtime/downtime.html` would be kept as is but for others who overloaded the template they could choose to display these pieces of information.

Thoughts?

**Comment by dstegelman** [comment]
Hi, thanks for the question. 

Yes, I do think that would be something that would add value.  Feel free to open a PR.
