### ISSUE TITLE
cannot pip install version 1.1.0

### ISSUE THREAD

**Issue by panosmm** [dstegelman/django-downtime#40]
Hey, thanks for the great tool. I'm trying to switch to 1.1.0 do upgrade to django 1.9 and getting:

Could not find a version that satisfies the requirement django-downtime==1.1.0 (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4)
No matching distribution found for django-downtime==1.1.0

**Comment by dstegelman** [comment]
I haven't released this version yet on pypi. 1.1.0 is the latest development version.
