### ISSUE TITLE
Support new Django middleware style

### ISSUE THREAD

**Issue by peterfarrell** [dstegelman/django-downtime#41]
Add support for new Django middleware that started in Django 1.10. Willing to do a pull request if it's possible to get a new release soon.

[Django Middleware - 1.10](https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-middleware)

**Comment by peterfarrell** [comment]
I put in PR #42 to upgrade support.

**Comment by dstegelman** [comment]
https://github.com/dstegelman/django-downtime/releases/tag/1.1.1
